"""
Newsletter Pipeline — RSS to email newsletter with LLM curation.
Creates curated email digests from RSS feeds, scores articles, selects top N,
and sends via SMTP or Resend.
"""
import json
import re
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path


def _score_article(article, topic_keywords=None):
    score = 0
    title = (article.get("title") or "").lower()
    body = (article.get("body") or article.get("summary") or "").lower()
    if topic_keywords:
        kw_matches = sum(1 for kw in topic_keywords if kw.lower() in (title + " " + body))
        score += kw_matches * 8
    if len(title) > 10:
        score += 3
    if len(body) > 200:
        score += 5
    if any(w in title for w in ["ai", "agent", "llm", "model", "tool"]):
        score += 5
    if article.get("url"):
        score += 2
    return score


def curate_articles(items, max_selected=10, keywords=None):
    scored = [(item, _score_article(item, keywords)) for item in items]
    scored.sort(key=lambda x: x[1], reverse=True)
    selected = [item for item, _ in scored[:max_selected]]
    for i, item in enumerate(selected):
        item["rank"] = i + 1
    return selected


def render_html(items, title="Daily Digest", description=""):
    rows = ""
    for item in items:
        summary = (item.get("summary") or item.get("body") or "")[:200]
        link = item.get("url", "")
        rows += f'<li><a href="{link}"><strong>{item.get("title", "Untitled")}</strong></a><br>{summary}</li>\n'
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{title}</title></head>
<body style="font-family:system-ui,sans-serif;max-width:640px;margin:0 auto;padding:20px">
<h1>{title}</h1>
<p>{description}</p>
<ul>{rows}</ul>
<p style="color:#888;font-size:12px">Generated by ai-self-media-tools on {datetime.now().strftime('%Y-%m-%d')}</p>
</body></html>"""


def send_smtp(html_body, subject, to_addrs, smtp_host, smtp_port, smtp_user, smtp_pass, from_addr):
    import smtplib
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = ", ".join(to_addrs) if isinstance(to_addrs, list) else to_addrs
    msg.attach(MIMEText(html_body, "html", "utf-8"))
    with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as server:
        server.starttls()
        server.login(smtp_user, smtp_pass)
        server.send_message(msg)
    return {"ok": True, "sent_to": to_addrs}


def pipeline(feed_urls, keywords=None, max_selected=10, config=None):
    from .rss_ingest import ingest_multi
    cfg = config or {}
    result = ingest_multi(feed_urls)
    if not result["ok"]:
        return {"ok": False, "error": "rss_fetch_failed", "details": result.get("errors", [])}
    curated = curate_articles(result.get("items", []), max_selected, keywords)
    html = render_html(curated, title=cfg.get("title", "Daily Digest"),
                       description=cfg.get("description", ""))
    output_dir = Path(cfg.get("data_dir", "/tmp")) / "newsletters"
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"digest-{datetime.now().strftime('%Y%m%d')}.html"
    path.write_text(html, encoding="utf-8")
    result = {"ok": True, "selected": len(curated), "total": result["total_items"],
              "html_path": str(path)}
    smtp = cfg.get("smtp", {})
    if smtp.get("host"):
        r = send_smtp(html, cfg.get("title", "Daily Digest"), smtp.get("to", []),
                      smtp["host"], smtp.get("port", 587), smtp.get("user", ""),
                      smtp.get("pass", ""), smtp.get("from", "newsletter@localhost"))
        result["email"] = r
    return result
