"""Zhihu companion-pin generation and anti-spam validation.

Zhihu pins are short-form discussion starters. They must not be generated by
copying an article opening paragraph, because that creates a high-similarity
promotion item and can be classified as low-value repeated content.
"""

from __future__ import annotations

import hashlib
import re
from typing import Any

from .zhihu_cli_adapter import ZhihuCliAdapter, ZhihuCliError

MAX_PIN_TITLE_CHARS = 28
MIN_PIN_CONTENT_CHARS = 80
MAX_PIN_CONTENT_CHARS = 360
MAX_SOURCE_OVERLAP = 0.22
MAX_TITLE_OVERLAP = 0.55
COPIED_FRAGMENT_CHARS = 18


class ZhihuPinValidationError(ZhihuCliError):
    """Raised when a generated pin would risk spam/high-similarity limits."""


def _clean(text: str) -> str:
    return re.sub(r"\s+", " ", str(text or "")).strip()


def _plain(text: str) -> str:
    text = re.sub(r"https?://\S+", "", str(text or ""))
    text = re.sub(r"[#>*_`~\[\](){}|]", " ", text)
    return _clean(text)


def _strip_md_title(text: str) -> str:
    lines = str(text or "").splitlines()
    while lines and lines[0].lstrip().startswith("#"):
        lines.pop(0)
    return "\n".join(lines)


def _norm_chars(text: str) -> str:
    return re.sub(r"\s+", "", _plain(text).casefold())


def _char_ngrams(text: str, n: int = 4) -> set[str]:
    chars = _norm_chars(text)
    if len(chars) < n:
        return {chars} if chars else set()
    return {chars[i : i + n] for i in range(len(chars) - n + 1)}


def _ngram_overlap(left: str, right: str) -> float:
    a = _char_ngrams(left)
    b = _char_ngrams(right)
    if not a or not b:
        return 0.0
    return round(len(a & b) / max(1, len(a | b)), 3)


def _contains_copied_fragment(pin_text: str, source_text: str) -> bool:
    pin = _norm_chars(pin_text)
    source = _norm_chars(source_text)
    if not pin or not source:
        return False
    step = max(1, COPIED_FRAGMENT_CHARS // 2)
    for idx in range(0, max(0, len(source) - COPIED_FRAGMENT_CHARS + 1), step):
        frag = source[idx : idx + COPIED_FRAGMENT_CHARS]
        if len(frag) >= COPIED_FRAGMENT_CHARS and frag in pin:
            return True
    return False


def _topic_label(title: str, job: dict[str, Any]) -> str:
    raw = _clean(job.get("topic") or title or "AI workflow")
    raw = re.split(r"[:：|｜\-—]", raw, maxsplit=1)[0]
    raw = re.sub(r"[^\w\u4e00-\u9fff]+", "", raw)
    return raw[:14] or "AI workflow"


def _variant_index(seed: str, count: int) -> int:
    digest = hashlib.sha256(seed.encode("utf-8", errors="ignore")).hexdigest()
    return int(digest[:8], 16) % max(1, count)


def _pin_title(article_title: str, job: dict[str, Any]) -> str:
    topic = _topic_label(article_title, job)
    variants = [
        f"{topic}: one real question",
        f"{topic}: what changed my mind",
        f"{topic}: the hidden tradeoff",
        f"{topic}: one takeaway",
    ]
    title = variants[_variant_index(article_title + topic, len(variants))]
    return title[:MAX_PIN_TITLE_CHARS]


def _pin_body(article_title: str, article_url: str, extra: str, job: dict[str, Any]) -> str:
    topic = _topic_label(article_title, job)
    payoff = _clean(
        (job.get("strategy_brief") or {}).get("reader_payoff")
        or (job.get("draft_meta") or {}).get("reader_payoff")
        or "turn a vague AI workflow into a repeatable checklist"
    )
    angles = [
        (
            f"I am not reposting the article here. The useful part is one decision point about {topic}: "
            f"where should AI stop, and where should a human check the result?"
        ),
        (
            f"My main note on {topic}: the tool itself is rarely the bottleneck. "
            f"The real difference is whether the workflow has clear acceptance checks."
        ),
        (
            f"This is the part of {topic} I would discuss first with another builder: "
            f"what evidence proves the workflow is actually saving time?"
        ),
        (
            f"The article is a longer breakdown. The short version: {topic} only works when the failure cases "
            f"are written down before automation starts."
        ),
    ]
    body = angles[_variant_index(article_title + payoff, len(angles))]
    lines = [
        body,
        f"Reader payoff: {payoff[:90]}",
        "Question: which step would you still keep manual after trying this?",
    ]
    if article_url:
        lines.append(article_url)
    if extra:
        lines.append(_clean(extra)[:90])
    return "\n".join(lines)


def build_pin_text(job: dict[str, Any], article_url: str = "", extra: str = "") -> dict[str, Any]:
    """Generate a review-safe Zhihu pin payload from an article job.

    The payload includes validation evidence so callers can log why a pin was
    safe enough for review or publishing.
    """
    article_title = _clean(job.get("title") or "")
    payload = {
        "title": _pin_title(article_title, job),
        "content": _pin_body(article_title, _clean(article_url), extra, job),
    }
    payload["validation"] = validate_pin_payload(job, payload, article_url=article_url, strict_publish=False)
    if not payload["validation"]["passed"]:
        fallback = {
            "title": "One workflow question",
            "content": "\n".join(
                [
                    "I am keeping this pin separate from the long article: one question, one tradeoff, no copied excerpt.",
                    "If a workflow claims to save time, the key test is whether it still works after the first messy real case.",
                    "Question: what would you ask before trusting this kind of AI workflow?",
                    _clean(article_url),
                ]
            ).strip(),
        }
        fallback["validation"] = validate_pin_payload(job, fallback, article_url=article_url, strict_publish=False)
        return fallback
    return payload


def validate_pin_payload(
    job: dict[str, Any],
    payload: dict[str, Any],
    article_url: str = "",
    strict_publish: bool = False,
) -> dict[str, Any]:
    title = _clean(payload.get("title") or "")
    content = _clean(payload.get("content") or "")
    article_title = _clean(job.get("title") or "")
    article_body = _plain(_strip_md_title(job.get("body") or ""))
    source_text = f"{article_title} {article_body}"
    source_overlap = _ngram_overlap(content, source_text)
    title_overlap = _ngram_overlap(title, article_title)
    copied_fragment = _contains_copied_fragment(content, article_body)
    failures: list[str] = []

    if not title:
        failures.append("pin_title_missing")
    if len(title) > MAX_PIN_TITLE_CHARS:
        failures.append("pin_title_too_long")
    if _norm_chars(title) == _norm_chars(article_title):
        failures.append("pin_title_reuses_article_title")
    if len(_norm_chars(content)) < MIN_PIN_CONTENT_CHARS:
        failures.append("pin_content_too_short")
    if len(content) > MAX_PIN_CONTENT_CHARS:
        failures.append("pin_content_too_long")
    if source_overlap > MAX_SOURCE_OVERLAP:
        failures.append("pin_content_too_similar_to_article")
    if title_overlap > MAX_TITLE_OVERLAP:
        failures.append("pin_title_too_similar_to_article")
    if copied_fragment:
        failures.append("pin_contains_copied_article_fragment")
    if "?" not in content and "？" not in content:
        failures.append("pin_discussion_question_missing")
    if strict_publish and not _clean(article_url):
        failures.append("pin_publish_requires_visible_article_url")

    return {
        "passed": not failures,
        "failures": failures,
        "metrics": {
            "content_chars": len(_norm_chars(content)),
            "title_chars": len(title),
            "source_overlap": source_overlap,
            "title_overlap": title_overlap,
            "copied_fragment": copied_fragment,
        },
        "policy": {
            "max_source_overlap": MAX_SOURCE_OVERLAP,
            "max_title_overlap": MAX_TITLE_OVERLAP,
            "min_content_chars": MIN_PIN_CONTENT_CHARS,
            "max_content_chars": MAX_PIN_CONTENT_CHARS,
            "copied_fragment_chars": COPIED_FRAGMENT_CHARS,
        },
    }


def publish_article_pin(
    job: dict[str, Any],
    article_url: str = "",
    extra: str = "",
    images: list | None = None,
    timeout: int = 60,
) -> dict[str, Any]:
    """Publish a validated companion pin via the Zhihu CLI adapter."""
    payload = build_pin_text(job, article_url=article_url, extra=extra)
    validation = validate_pin_payload(job, payload, article_url=article_url, strict_publish=True)
    if not validation["passed"]:
        raise ZhihuPinValidationError("zhihu pin validation failed: " + ", ".join(validation["failures"]))
    adapter = ZhihuCliAdapter(timeout=timeout)
    result = adapter.publish_pin(payload["title"], content=payload["content"], images=images)
    result["validation"] = validation
    return result
